image: "ruby:2.4"

stages:
  - test
  - publish
# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - ruby -v 
  - gem install bundler  --no-ri --no-rdoc    
  - bundle install

# Optional - Delete if not using `rubocop`
rubocop:
  stage: test
  script:
  - rubocop

rspec:
  stage: test
  script:
  - rspec spec

# Use dpl to publish the tem
rubygems:
  stage: publish
  only: 
  - master
  environment: 
    name: rubygems
    url: https://rubygems.org/gems/pdground
  script:
  - gem install dpl
  - dpl --provider=rubygems --api-key=$RUBYGEMS_KEY
